-   id: typescript-eslint
    name: typescript-eslint
    entry: eslint
    language: node
    'types': [file]
    files: \.(ts|tsx)$
    args: []
    require_serial: false
    additional_dependencies:
      - eslint@6.6.0
      - '@typescript-eslint/eslint-plugin@2.6.0'
      - '@typescript-eslint/parser@2.6.0'
      - eslint-config-airbnb@16.1.0
      - eslint-config-prettier@6.5.0
      - eslint-plugin-babel@5.2.1
      - eslint-plugin-import@2.18.2
      - eslint-plugin-jsx-a11y@6.2.3
      - eslint-plugin-prettier@3.1.1
      - eslint-plugin-react@7.16.0
      - eslint-plugin-react-hooks@1.6.1
